### ISSUE TITLE
error: unable to build "the-way" as I cannot build "skim" but I already have "skim" installed.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [out-of-cheese-error/the-way#96] opened 2021-02-15 08:32 UTC
first thank you!
works great on my pc, tried building on aarch64 and as title says, it fails to build "skim", yet I can (and have) built & installed "skim" already.

**Comment by Ninjani** [comment] 2021-02-15 18:01
Thanks for trying this out! Which OS are you targeting? And which version of skim could you build/install?

**Comment by 5c0tt-b0t** [comment] 2021-02-16 19:11
I am trying to build this on my Android tablet (aarch64 ARM).
I built `skim` version `0.9.3` on it already.
Does this need to be compiled along with `skim`? or are there some values that I could change to omit `skim` from make files? and use the `skim` binary thats already on my path?

**Thank you!** `the-way` really is *the* way.
Its appreciated!

**Comment by Ninjani** [comment] 2021-02-17 10:51
I tried this on my Android tablet - the issue isn't with `skim` but with the copy command used by the-way. Right now this uses `xclip` on linux and `pbcopy` on mac, but there isn't anything set for Android. I'm working on a fix now that will use `termux-clipboard-set` for android - this needs the `termux-api` pkg and the Termux:API app from the appstore, along with Termux. Would this kind of setup work for you? I'm assuming that you're using Termux but let me know if you have a different setup.

>Its appreciated!

Thank you, I'm glad you're finding it useful!

**Comment by 5c0tt-b0t** [comment] 2021-02-17 21:43
**Thank you!** yes, thats perfect! I'm using Termux/API (F-droid version) already.
Finally... I can carry all my snippets around with me! on my little 9" tablet.... thats more portability than POSIX! 🤣
 Hopefully you get more use out of your tablet now as well!

**Comment by Ninjani** [comment] 2021-02-18 17:10
This should be fixed now on master - can you try again? If not please reopen the issue and I'll take another look.

>Hopefully you get more use out of your tablet now as well!

Yes, great idea!

**Closed** 2021-02-18 17:10 UTC

**Comment by 5c0tt-b0t** [comment] 2021-02-19 10:02
Working perfectly! **thank you!**
